# app/dao/metadata_dao.py

class MetadataDao:
    """
    Tables/colonnes basées sur la nomenclature (codev_nomenclature.csv).
    On expose des noms normalisés snake_case lowercase.
    """

    def get_tables(self) -> list[str]:
        return [
            "insertion",
            "etudiants",
            "mobilite",
        ]

    def get_columns(self, table: str) -> list[str]:
        columns: dict[str, list[str]] = {
            "insertion": [
                "code",
                "date",
                "promotion",
                "formation",
                "specialite",
                "genre",
                "age",
                "nationalite",
                "bac",
                "csp",
                "reponse",
                "situation_mars",
                "recherche_emploi_depuis",
                "refus_plusieurs_emplois",
                "type_etude",
                "type_etude_autre",
                "secteur_cifre",
                "secteur_cifre_autre",
                "intitule_formation",
                "etablissement_formation",
                "situation_represente",
                "situation_represente_autre",
                "egalement_recherche_emploi",
                "premier_emploi_depuis_diplome",
                "situation",
                "situation_inactive_depuis",
                "num_emploi",
                "temps_pour_premier_emploi",
                "moyen_trouver_emploi",
                "moyen_trouver_emploi_autre",
                "employeur",
                "employeur_autre",
                "secteur_activite_organisme",
                "type_emploi",
                "type_emploi_autre",
                "type_volontariat",
                "type_volontariat_autre",
                "statut_emploi",
                "condition_depart_entreprise",
                "condition_depart_entreprise_autre",
                "objectif_premier_emploi",
                "objectif_premier_emploi_autre",
                "intitule_emploi",
                "responsabilite_hierarchique",
                "responsabilite_projet",
                "responsabilite_equipe",
                "responsabilite_budget",
                "mission_rse",
                "mission_rse_environnement",
                "mission_rse_egalite",
                "mission_rse_handicap",
                "mission_rse_ouverture",
                "mission_rse_ethique",
                "mission_rse_autre",
                "moyen_trouver_emploi_2",
                "moyen_trouver_emploi_autre_2",
                "critere_principal",
                "critere_principal_autre",
                "duree_trouver_emploi",
                "employeur_2",
                "employeur_2_autre",
                "employeur_2_type",
                "taille_organisme_2",
                "secteur_activite_organisme_2",
                "type_emploi_2",
                "statut_emploi_autre_2",
                "createur_entreprise",
                "activite_principale",
                "type_volontariat_2",
                "type_volontariat_autre_2",
                "statut_emploi_2",
                "fonction_emploi_2",
                "fonction_emploi_autre_2",
                "temps_travail",
                "heure_par_semaine",
                "teletravail",
                "moyenne_jours_teletravail",
                "departement",
                "pays",
                "ville",
                "emploi_represente_2",
                "emploi_represente_autre_2",
                "recherche_emploi",
                "raison_recherche_emploi",
            ],
            "etudiants": [
                "centre",
                "composante",
                "iae_etape_code",
                "iae_version_code",
                "iae_etape_lib",
                "id_polytech",
                "redoublant",
                "sexe",
                "age",
                "nationalite",
                "bac",
                "bac_annee",
                "bac_mention",
                "bac_lieu",
                "titre_access",
                "titre_acces_iea",
                "titre_acces_pays",
                "boursier",
                "dernier_etablissement_code",
                "dernier_etablissement_lib",
                "premier_etablissement_code",
                "premier_etablissement_lib",
                "type_dernier_diplome_code",
                "type_dernier_diplome_lib",
                "regime_inscription",
            ],
            "mobilite": [
                "id_polytech_inter",
                "sexe",
                "filiere",
                "cursus",
                "nationalite",
                "diplome",
                "stage_3a",
                "stage_4a",
                "s9_5a",
                "stage_5a",
                "double_diplome",
                "sejourt_court",
                "cesure",
                "substitution",
                "nb_mois_stage",
                "nb_mois_etude",
                "commentaires",
                "total",
            ],
        }
        return columns.get(table, [])

    def get_columns_for_tables(self, tables: list[str]) -> list[str]:
        result = set()
        for t in tables:
            result.update(self.get_columns(t))
        return list(result)
